# Generated by Django 5.1.1 on 2024-10-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='timestamped_transcript',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
