# Generated by Django 5.1.1 on 2024-10-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_podcast_timestamped_transcript'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='structured_transcript',
            field=models.TextField(default='[]'),
        ),
    ]
