# Generated by Django 5.1.1 on 2024-10-05 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_podcast_structured_transcript'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='structured_transcript',
        ),
    ]
