# Generated by Django 5.1.1 on 2024-10-05 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_podcast_structured_transcript'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='formatted_transcript',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
